// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Cliente
{
    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string tipo { get; set; }

    public string direccion { get; set; }

    public string zona { get; set; }

    public bool? clasificacion_automatica { get; set; }

    public virtual ICollection<Orden> Orden { get; set; } = new List<Orden>();
}