// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Detalle_Orden
{
    public int id_detalle_orden { get; set; }

    public int? id_orden { get; set; }

    public int? id_producto { get; set; }

    public int cantidad { get; set; }

    public decimal? subtotal { get; set; }

    public virtual Orden id_ordenNavigation { get; set; }

    public virtual Producto id_productoNavigation { get; set; }
}