// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Detalle_pedido
{
    public int id_producto { get; set; }

    public int id_proveedor { get; set; }

    public string descripcion { get; set; }

    public virtual Producto id_productoNavigation { get; set; }

    public virtual Proveedor id_proveedorNavigation { get; set; }
}