// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Empleado
{
    public int id_empleado { get; set; }

    public string nombre { get; set; }

    public string rol { get; set; }

    public virtual ICollection<Orden> Orden { get; set; } = new List<Orden>();
}