// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Orden
{
    public int id_orden { get; set; }

    public int? id_cliente { get; set; }

    public int? id_empleado { get; set; }

    public DateTime? fecha { get; set; }

    public string metodo_pago { get; set; }

    public decimal? total { get; set; }

    public virtual ICollection<Detalle_Orden> Detalle_Orden { get; set; } = new List<Detalle_Orden>();

    public virtual Cliente id_clienteNavigation { get; set; }

    public virtual Empleado id_empleadoNavigation { get; set; }
}