// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Producto
{
    public int id_producto { get; set; }

    public string nombre { get; set; }

    public string categoria { get; set; }

    public decimal precio { get; set; }

    public int stock { get; set; }

    public virtual ICollection<Detalle_Orden> Detalle_Orden { get; set; } = new List<Detalle_Orden>();

    public virtual ICollection<Detalle_pedido> Detalle_pedido { get; set; } = new List<Detalle_pedido>();
}