// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class DulceFacil2DBContext : DbContext
{
    public DulceFacil2DBContext()
    {
    }

    public DulceFacil2DBContext(DbContextOptions<DulceFacil2DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Detalle_Orden> Detalle_Orden { get; set; }

    public virtual DbSet<Detalle_pedido> Detalle_pedido { get; set; }

    public virtual DbSet<Empleado> Empleado { get; set; }

    public virtual DbSet<Orden> Orden { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Proveedor> Proveedor { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=DulceFacil2;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__Cliente__677F38F5D9773D47");

            entity.Property(e => e.clasificacion_automatica).HasDefaultValue(false);
            entity.Property(e => e.direccion).HasMaxLength(200);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.tipo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.zona).HasMaxLength(100);
        });

        modelBuilder.Entity<Detalle_Orden>(entity =>
        {
            entity.HasKey(e => e.id_detalle_orden).HasName("PK__Detalle___D2FC3FD7D781A20B");

            entity.Property(e => e.subtotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_ordenNavigation).WithMany(p => p.Detalle_Orden)
                .HasForeignKey(d => d.id_orden)
                .HasConstraintName("FK__Detalle_O__id_or__4CA06362");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.Detalle_Orden)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK__Detalle_O__id_pr__4D94879B");
        });

        modelBuilder.Entity<Detalle_pedido>(entity =>
        {
            entity.HasKey(e => new { e.id_producto, e.id_proveedor }).HasName("PK__Detalle___67E7C3EF11D084E6");

            entity.Property(e => e.descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.Detalle_pedido)
                .HasForeignKey(d => d.id_producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_p__id_pr__3F466844");

            entity.HasOne(d => d.id_proveedorNavigation).WithMany(p => p.Detalle_pedido)
                .HasForeignKey(d => d.id_proveedor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_p__id_pr__403A8C7D");
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.id_empleado).HasName("PK__Empleado__88B5139405165A08");

            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.rol)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<Orden>(entity =>
        {
            entity.HasKey(e => e.id_orden).HasName("PK__Orden__DD5B8F33B3360CE4");

            entity.Property(e => e.fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.metodo_pago).HasMaxLength(20);
            entity.Property(e => e.total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.Orden)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK__Orden__id_client__47DBAE45");

            entity.HasOne(d => d.id_empleadoNavigation).WithMany(p => p.Orden)
                .HasForeignKey(d => d.id_empleado)
                .HasConstraintName("FK__Orden__id_emplea__48CFD27E");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__Producto__FF341C0D3CD2B2C6");

            entity.Property(e => e.categoria).HasMaxLength(100);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Proveedor>(entity =>
        {
            entity.HasKey(e => e.id_proveedor).HasName("PK__Proveedo__8D3DFE283D87A55B");

            entity.Property(e => e.contacto).HasMaxLength(100);
            entity.Property(e => e.direccion).HasMaxLength(200);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.telefono).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}